services:
- type: web
  name: noest-proxy
  env: docker
  dockerfilePath: ./Dockerfile
  plan: free
  autoDeploy: true
  envVars:
  - key: UPSTREAM_BASE
    value: https://app.noest-dz.com
  - key: ALLOWED_ORIGIN
    value: "*"
  - key: API_BEARER
    sync: false
  - key: NOEST_EMAIL
    sync: false
  - key: NOEST_PASSWORD
    sync: false
  - key: DEFAULT_TRACKING
    sync: false
  - key: DEFAULT_ALT_PHONE
    sync: false
